In [1]:
import numpy as np
import cv2

In [2]:
f = '/tmp/f2.jpg'

In [3]:
img = cv2.imread(f)

In [11]:
img.shape
show_img(img)

In [9]:
def show_img(img):
    cv2.imshow('image', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [7]:
# img

In [14]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blur = cv2.GaussianBlur(gray, (3,3), 0)

In [15]:
show_img(blur)

In [20]:
blur

array([[16, 17, 18, ..., 14, 16, 18],
       [15, 15, 17, ..., 13, 15, 17],
       [14, 14, 16, ..., 15, 15, 15],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=uint8)

In [16]:
edged = cv2.Canny(blur, 10, 30)

In [22]:
show_img(edged)

In [23]:
edged

array([[  0,   0,   0, ...,   0, 255,   0],
       [  0,   0,   0, ...,   0, 255, 255],
       [  0,   0,   0, ..., 255,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [25]:
contours,hierarchy = cv2.findContours(edged, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
for cnt in contours:
  length = cv2.arcLength(cnt,True)
  if length >= 1:
    cv2.drawContours(img,cnt,-1,(0,0,255),2)

In [26]:
show_img(img)

In [27]:
import cv2
import numpy as np
 
image = cv2.imread("/Users/xbkaishui/Desktop/chip_hh.jpg", 0)
hist = cv2.calcHist([image],
    [0], #使用的通道
    None, #没有使用mask
    [256], #HistSize
    [0.0,255.0]) #直方图柱的范围

In [29]:
image

array([[ 7, 21, 17, ...,  0,  0,  0],
       [ 3,  6, 21, ...,  0,  0,  0],
       [13, 27, 21, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=uint8)

In [31]:
hist.shape

(256, 1)

In [35]:
hist[3]

array([518.], dtype=float32)

In [39]:
def calcAndDrawHist(image, color):  
    hist= cv2.calcHist([image], [0], None, [256], [0.0,255.0])  
    minVal, maxVal, minLoc, maxLoc = cv2.minMaxLoc(hist)
    print(f"minVal {minVal}, maxVal {maxVal}")
    histImg = np.zeros([256,256,3], np.uint8)  
    hpt = int(0.9* 256);  
      
    for h in range(256):  
        intensity = int(hist[h]*hpt/maxVal)  
        cv2.line(histImg,(h,256), (h,256-intensity), color)  
          
    return histImg; 

In [40]:
img = cv2.imread("/Users/xbkaishui/Desktop/chip_hh.jpg")
b, g, r = cv2.split(img)  
  
histImgB = calcAndDrawHist(b, [255, 0, 0])  
histImgG = calcAndDrawHist(g, [0, 255, 0])  
histImgR = calcAndDrawHist(r, [0, 0, 255])  
      
cv2.imshow("histImgB", histImgB)  
cv2.imshow("histImgG", histImgG)  
cv2.imshow("histImgR", histImgR)  
cv2.imshow("Img", img)  
cv2.waitKey(0)  
cv2.destroyAllWindows() 

minVal 0.0, maxVal 76574.0
minVal 0.0, maxVal 76574.0
minVal 0.0, maxVal 76574.0
